export const CHAT_COLORS = {
    primary:           '#543C52',
    highlight:         '#E9E5EE',
    screenBg:          '#F3F4F6',
    cardBg:            '#FFFFFF',
    text:              '#070A1C',
    textMuted:         '#81818D',
    textLight:         '#999999',
    border:            '#EBEBEB',
    bubbleMine:        '#EDE8F2',
    bubbleOther:       '#FFFFFF',
    bubbleOtherBorder: '#EBEBEB',
    online:            '#4CAF50',
    badge:             '#E53935',
    dateBg:            '#E9E5EE',
} as const;